import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'app.dart';
import 'models/event.dart';
import 'models/birthday.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive
  await Hive.initFlutter();
  
  // Register Hive Adapters
  // Note: These classes are generated by hive_generator
  Hive.registerAdapter(EventAdapter());
  Hive.registerAdapter(BirthdayAdapter());

  // Open boxes
  await Hive.openBox<Event>('events');
  await Hive.openBox<Birthday>('birthdays');

  runApp(
    const ProviderScope(
      child: PlannerApp(),
    ),
  );
}
